import React, { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import ConstructionPopup from "../components/ConstructionPopup";
import Link from "next/link";

const helloArr = [
  "Hello",
  ",",
  " ",
  "I'm",
  " ",
  "Aayush",
  ",",
  " ",
  "student",
  ",",
  " ",
  "software engineer",
  ",",
  " ",
  "etc",
  ".",
];

export default function Home() {
  console.log(helloArr);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ConstructionPopup />
      <main className={styles.main}>
        <div className={styles.hello}>
          <div className={styles.left}>
            {helloArr.map((char, ind) => {
              return char !== " " ? (
                <div key={ind} className={styles.letter}>
                  {char}
                </div>
              ) : (
                <div key={ind} className={styles.space}></div>
              );
            })}
          </div>
          <div className={styles.right}>
            <h1>A</h1>
          </div>
        </div>

        <div className={styles.grid}>
          <Link href="/projects">
            <a className={styles.card}>
              <h2>Projects &rarr;</h2>
              <p>Check out some projects I&apos;ve worked on</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
